sudo: required

install:
  - sudo apt-get install -y leafpad

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "Xvfb :99 -screen 0 1024x768x24 +extension RANDR &"
  - sleep 3 # give xvfb some time to start
    
  
script:  
  - leafpad "test"
  - leafpad "one"
  - leafpad "two"
  - leafpad "three"
  - xlsclients -l

