sudo: required

install:
  - sudo apt-get install -y leafpad
  - sudo apt-get install -y gedit

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
    
  
script:  
  - gedit test
  - leafpad one
  - xlsclients -l

