sudo: require

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install cowsay

script:
  - echo "Hoi ik ben Jorn en das echt vet vet!"
  - echo "Hello!"
  - echo "Salut!"
  - cowsay "Hallo Jorn"
