{
  "sudo": "required",
  "dist": "trusty",
  "before_install": [
    "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x24 +extension RANDR"
  ],
  "install": [
    "sudo apt-get install -y leafpad"
  ],
  "before_script": [
    "export DISPLAY=:99.0",
    "sleep 3"
  ],
  "script": [
    "phantomjs testrunner.js",
    "sleep 5",
    "leafpad test &",
    "sleep 2",
    "xlsclients -l"
  ],
  "language": "ruby",
  "group": "stable",
  "os": "linux"
}
